# Generated by Django 4.2.7 on 2025-11-22 15:57

from django.conf import settings
import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#4CAF50",
                        help_text="Hex color for habit display",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier for habit", max_length=50
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                (
                    "target_days",
                    models.IntegerField(
                        default=7,
                        help_text="Target days per week (for weekly habits)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "recurrence",
                    recurrence.fields.RecurrenceField(
                        blank=True,
                        help_text="Custom recurrence pattern for habits",
                        null=True,
                    ),
                ),
                ("sort_order", models.FloatField(default=0.0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether habit is currently being tracked",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "habits",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#1E90FF",
                        help_text="Hex color code (e.g., #1E90FF for blue)",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier (e.g., emoji or icon class name)",
                        max_length=50,
                    ),
                ),
                (
                    "sort_order",
                    models.FloatField(
                        default=0.0,
                        help_text="Float field for efficient drag-and-drop reordering",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lists",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#808080",
                        help_text="Hex color code for tag display",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the habit check-in")),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether habit was completed on this date",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the habit completion",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tasks.habit",
                    ),
                ),
            ],
            options={
                "db_table": "habit_logs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=500)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Rich text notes/description for the task"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Due date and time for the task",
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start date for calendar time-blocking",
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in minutes for time-blocking",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "recurrence",
                    recurrence.fields.RecurrenceField(
                        blank=True,
                        help_text='RFC 5545 RRULE for recurring tasks (e.g., "Every 3rd Friday")',
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(0, "None"), (1, "Low"), (2, "Medium"), (3, "High")],
                        default=0,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                (
                    "kanban_order",
                    models.FloatField(
                        default=0.0,
                        help_text="Float field allows inserting tasks between others without rewriting all rows",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="tasks.list",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="tasks.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["kanban_order", "created_at"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["title"],
                        name="task_title_gin_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["notes"],
                        name="task_notes_gin_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                    models.Index(fields=["due_date"], name="task_due_date_idx"),
                    models.Index(fields=["priority"], name="task_priority_idx"),
                    models.Index(fields=["status"], name="task_status_idx"),
                    models.Index(fields=["user", "due_date"], name="task_user_due_idx"),
                    models.Index(
                        fields=["user", "status"], name="task_user_status_idx"
                    ),
                    models.Index(
                        fields=["user", "list", "kanban_order"],
                        name="task_user_list_order_idx",
                    ),
                    models.Index(fields=["path"], name="task_path_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["user"], name="tag_user_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="list",
            index=models.Index(
                fields=["user", "sort_order"], name="user_list_order_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="list",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="habitlog",
            index=models.Index(fields=["habit", "date"], name="habit_log_date_idx"),
        ),
        migrations.AddIndex(
            model_name="habitlog",
            index=models.Index(
                fields=["habit", "completed"], name="habit_log_completed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="habitlog",
            unique_together={("habit", "date")},
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_active"], name="habit_user_active_idx"
            ),
        ),
    ]
