# Generated by Django 4.2.7 on 2025-12-19 06:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                            ("appealed", "Appealed"),
                            ("under_review", "Under Review"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "stake_type",
                    models.CharField(
                        choices=[
                            ("social", "Social Accountability"),
                            ("points", "Virtual Points"),
                            ("money", "Real Money"),
                        ],
                        db_index=True,
                        default="social",
                        help_text="Type of stake: social pressure, virtual points, or real money",
                        max_length=20,
                    ),
                ),
                (
                    "stake_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount at stake (required for money type)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupees"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "leniency",
                    models.CharField(
                        choices=[
                            ("lenient", "Lenient - Easy appeal requirements"),
                            ("normal", "Normal - Standard appeal requirements"),
                            ("hard", "Hard - Strict appeal requirements"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("evidence_required", models.BooleanField(default=True)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo Upload"),
                            ("timelapse_video", "Timelapse Video"),
                            ("self_verification", "Self-Verification"),
                            ("manual", "Manual Verification"),
                        ],
                        default="self_verification",
                        max_length=30,
                    ),
                ),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="commitment_evidence/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp4",
                                    "mov",
                                    "avi",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "evidence_text",
                    models.TextField(
                        blank=True, help_text="Text evidence (notes, description, etc.)"
                    ),
                ),
                ("evidence_submitted", models.BooleanField(default=False)),
                ("evidence_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("complaints_flagged", models.BooleanField(default=False)),
                ("complaint", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.OneToOneField(
                        help_text="The task this commitment is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commitment",
                "verbose_name_plural": "Commitments",
                "db_table": "commitments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_more_info", "Needs More Information"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on verification"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commitment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_verification",
                        to="commitments.commitment",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who verified this evidence",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_evidences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Verification",
                "verbose_name_plural": "Evidence Verifications",
                "db_table": "commitment_evidence_verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="commitment__status_c5e311_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("technical_issue", "Technical Issue"),
                            ("emergency", "Emergency/Unforeseen Circumstance"),
                            ("illness", "Illness"),
                            ("evidence_issue", "Evidence Submission Issue"),
                            ("deadline_dispute", "Deadline Dispute"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed explanation of the complaint"),
                ),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True,
                        help_text="Supporting evidence for the complaint",
                        null=True,
                        upload_to="complaint_evidence/%Y/%m/%d/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved - Refund Granted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on the review decision"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("refund_processed", models.BooleanField(default=False)),
                ("refund_processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="commitments.commitment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this complaint",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint",
                "verbose_name_plural": "Complaints",
                "db_table": "commitment_complaints",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="commitment__user_id_8f561a_idx"
                    ),
                    models.Index(
                        fields=["commitment", "status"],
                        name="commitment__commitm_63870b_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["status", "created_at"], name="commitments_status_ead5b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["stake_type", "status"], name="commitments_stake_t_ad82ea_idx"
            ),
        ),
    ]
