# Generated by Django 4.2.7 on 2025-12-29 19:51

import apps.commitments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commitments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitmentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("evidence", "Evidence"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        default="evidence",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attached file",
                        upload_to=apps.commitments.models.commitment_attachment_path,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the attachment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="commitments.commitment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_commitment_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "commitment_attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["commitment", "attachment_type"],
                        name="commit_attach_type_idx",
                    ),
                    models.Index(
                        fields=["commitment", "created_at"],
                        name="commit_attach_created_idx",
                    ),
                ],
            },
        ),
    ]
