# Generated by Django 5.2.7 on 2025-11-12 08:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('one_time', 'One-time'), ('custom', 'Custom')], default='one_time', max_length=20)),
                ('custom_days', models.CharField(blank=True, help_text='Comma-separated days (MON,TUE,WED,...)', max_length=20)),
                ('stake_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='Rupees', max_length=10)),
                ('leniency', models.CharField(choices=[('lenient', 'Lenient - Easy appeal requirements'), ('normal', 'Normal - Standard appeal requirements'), ('hard', 'Hard - Strict appeal requirements')], default='normal', max_length=10)),
                ('evidence_required', models.BooleanField(default=True)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo Upload'), ('timelapse_video', 'Timelapse Video'), ('self_verification', 'Self-Verification'), ('manual', 'Manual Verification')], default='self_verification', max_length=30)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='contract_evidence/%Y/%m/%d/')),
                ('evidence_text', models.TextField(blank=True, help_text='Text evidence (notes, description, etc.)')),
                ('evidence_submitted', models.BooleanField(default=False)),
                ('evidence_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('complaints_flagged', models.BooleanField(default=False)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('appealed', 'Appealed'), ('under_review', 'Under Review')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commitment',
                'verbose_name_plural': 'Commitments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='commitments_user_id_0eb646_idx'), models.Index(fields=['start_time', 'end_time'], name='commitments_start_t_45fe03_idx')],
            },
        ),
    ]
