# Generated by Django 4.2.7 on 2025-12-01 19:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
        ("commitments", "0002_complaint_evidenceverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitment",
            name="stake_type",
            field=models.CharField(
                choices=[
                    ("social", "Social Accountability"),
                    ("points", "Virtual Points"),
                    ("money", "Real Money"),
                ],
                db_index=True,
                default="social",
                help_text="Type of stake: social pressure, virtual points, or real money",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="task",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional: Task that this commitment is linked to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commitment",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="commitment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("INR", "Indian Rupees"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="commitment",
            name="stake_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount at stake (required for money type)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["status", "end_time"], name="commitments_status_eb2d98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["user", "stake_type"], name="commitments_user_id_8cfffa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["user", "stake_type", "status"],
                name="commitments_user_id_127411_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="commitment",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gt", models.F("start_time"))),
                name="end_time_after_start_time",
            ),
        ),
    ]
