# Generated by Django 4.2.7 on 2025-12-01 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commitments", "0003_commitment_stake_type_commitment_task_and_more"),
    ]

    operations = []
